### ISSUE TITLE
Missing double letter marked as correct when should be incorrect

### ISSUE THREAD

**Issue by mdavis-xyz** [DerDemystifier/AnkiIgnoreCase#1]
If the correct answer has two letters in a row that are the same, and I only type one, I should be marked as incorrect. Without this extension I am marked as incorrect. But with the extension it marks me as correct, but only sometimes. Same with the other way around.

Here I omitted a `t` with the extension and it shows as correct:

![missing-t-with-extension](https://github.com/DerDemystifier/AnkiIgnoreCase/assets/7035647/44cac090-b148-4f74-8e7b-a2e98e7e966d)

Here I omitted a `t` without the extension and it shows as incorrect (expected behavior)

![missing-t-without-extension](https://github.com/DerDemystifier/AnkiIgnoreCase/assets/7035647/d25be3ff-07a3-4852-b6e1-246177fb130b)

And in reverse, here this should mark me as wrong for adding an extra `l`:

![missing-l-with-extension](https://github.com/DerDemystifier/AnkiIgnoreCase/assets/7035647/43eabfdf-ba60-4489-b18c-debf060528f2)

That was on  Android. On Linux (Ubuntu) I see the same behavior.
With the extension:

![Screenshot from 2023-05-12 08-37-16](https://github.com/DerDemystifier/AnkiIgnoreCase/assets/7035647/5bf13fcd-73f8-4b41-9a39-5ead4e9522a6)

Without:

![Screenshot from 2023-05-12 08-46-15](https://github.com/DerDemystifier/AnkiIgnoreCase/assets/7035647/98d61a5d-436a-4d16-877a-f421ddf7fed5)

Although if I am missing a letter, but everything is the right case, I *do* get the expected behavior.

![Screenshot from 2023-05-12 08-47-26](https://github.com/DerDemystifier/AnkiIgnoreCase/assets/7035647/f8dc89f3-3a4f-48f4-9b6d-8d42c20423a2)

If the letter in the wrong case is not adjacent to the double letters, I also get the expected behavior:

![Screenshot from 2023-05-12 08-48-09](https://github.com/DerDemystifier/AnkiIgnoreCase/assets/7035647/c0047583-8926-41b9-8031-b2e760faa5a8)

**Desktop (please complete the following information):**
Anki 2.1.61 (0c1eaf4c) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
    Platform: Linux-5.19.0-41-generic-x86_64-with-glibc2.36
    Flags: frz=True ao=False sv=2
    Add-ons, last update check: 2023-05-12 08:33:30

Since this happens on AndiDroid too, I suspect it's not related to this specific version of Anki.

Note that for security reasons I used the manual no-internet approach. So instead of installing the add-on, I just pasted the code, un-minified, into my cards.
e.g.

```
{{Image}}

<hr id=answer>

{{type:French}}

<!-- https://derdemystifier.github.io/AnkiIgnoreCase/ -->

<script>
(() => {
    "use strict";
    ! function() {
        const e = "code#typeans",
            t = e + ' > span[class^="type"]',
            o = e + ' br ~ span[class^="type"]';
        for (let e of document.querySelectorAll(t)) c(e);
        let r = Array.from(document.querySelectorAll(t)),
            n = Array.from(document.querySelectorAll(o)),
            s = r.filter((e => !n.includes(e)));
        if (i(s).toLowerCase() == i(n).toLowerCase()) {
            const t = document.querySelector(e);
            n.forEach((e => e.setAttribute("class", "typeGood"))), t.innerHTML = n.map((e => e.outerHTML)).join("")
        } else {
            for (var l = 0; l < (s.length < n.length ? s : n).length; l++) s[l].innerText.toLowerCase() == n[l].innerText.toLowerCase() && (s[l].setAttribute("class", "typeGood"), n[l].setAttribute("class", "typeGood"));
            const e = 3;
            for (; n.length;) {
                let t = [...s];
                for (; t.length >= e && n.length >= e;) {
                    const o = t.slice(0, e),
                        r = n.slice(0, e);
                    i(o).toLowerCase() == i(r).toLowerCase() ? (o.forEach((e => {
                        e.setAttribute("class", "typeGood")
                    })), r.forEach((e => {
                        e.setAttribute("class", "typeGood")
                    })), t.shift(), s = [...t], n.shift()) : t.shift()
                }
                n.shift()
            }
        }

        function c(e) {
            let t = e.innerText;
            for (let o = t.length - 1; o >= 0; o--) {
                let r = e.cloneNode(!0);
                r.innerHTML = t[o], e.parentNode.insertBefore(r, e.nextSibling)
            }
            e.remove()
        }

        function i(e) {
            return [...e].map((e => e.innerHTML)).join("")
        }
    }()
})();
</script>
```

**Comment by DerDemystifier** [comment]
Thanks for the nice formatting and images. I will see to this ASAP.

**Comment by DerDemystifier** [comment]
I'm using Anki 2.1.48 and it's working as expected on Desktop.
![image](https://github.com/DerDemystifier/AnkiIgnoreCase/assets/124774256/ffc00457-095c-4052-911c-4db49e2cbddf)

Anki apparently modified the comparison algorithm in version [2.1.58](https://changes.ankiweb.net/changes/2.1.50-59.html#changes-in-2158)
I guess I will need to update my Anki version and fix it. I will try to do that in the next few days. It's always a pain to move to a newer version as many addons stop working well.

**Comment by DerDemystifier** [comment]
Done! You can find the new script at [ignoreCase.min.js](https://derdemystifier.github.io/AnkiIgnoreCase/ignoreCase.min.js). 

![image](https://github.com/DerDemystifier/AnkiIgnoreCase/assets/124774256/d7a77dd1-d84a-4a69-b1c4-06bf11ea72e4)

_Side note_: July in French is Juillet not Julliet :)


The script is a bit longer after the fix and that's because I'm now using a library dedicated for diff comparisons.

You can always use the addon to alleviate the pain of copy/paste and to keep your card templates cleaner. (I still haven't updated the addon though).
