### ISSUE TITLE
Hyphen marked as incorrect after case difference ignored

### ISSUE THREAD

**Issue by mdavis-xyz** [DerDemystifier/AnkiIgnoreCase#4]
**Describe the bug**

I often see `-` characters coloured red when they are correct. This only happens when there is another character which is the wrong case.

**Input and Answer**
`a-bc`
↓
`A-bc`

**Expected Result**
Input is marked as correct. All green

**Actual Result**

`a` is marked as correct (desired behaviour) but `-` is marked as red (incorrect), which is not the desired behaviour.

**Screenshots**

![Screenshot from 2023-07-09 21-45-36](https://github.com/DerDemystifier/AnkiIgnoreCase/assets/7035647/01cb9f43-8e05-4f00-a980-31c324d78ce4)

Note that if the `A` at the start is the right case, then the `-` is marked correct. (So it's not the case that I'm typing `-` and the correct answer is a different unicode character that looks similar.)

![Screenshot from 2023-07-09 21-45-47](https://github.com/DerDemystifier/AnkiIgnoreCase/assets/7035647/57956c2b-1d5e-4063-8cff-de134a6e345b)

I've tried a simplified version. It happens with just `a-`->`A-`. And also `-a`->`-A`

**Desktop (please complete the following information):**
 - Anki Version :
Version ⁨2.1.61 (0c1eaf4c)⁩
Python 3.9.15 Qt 6.4.2 PyQt 6.4.0

I'm just modifying my cards with `<script src="https://derdemystifier.github.io/AnkiIgnoreCase/ignoreCase.min.js"></script>`

**Comment by DerDemystifier** [comment]
Done! I fixed this a couple of weeks ago but forgot to compile the src files. Finally done in [cfa9862](https://github.com/DerDemystifier/AnkiIgnoreCase/commit/cfa98628670cbfe6335e213431969f7477c8e3dc). 

Since you use `<script src="https://derdemystifier.github.io/AnkiIgnoreCase/ignoreCase.min.js"></script>`, it will work fine. No changes needed on your end.
